// Context Articles
export const SUCCESSFUL_GET_ARTICLES = 'SUCCESSFUL_GET_ARTICLES';
export const FAILED_GET_ARTICLES = 'FAILED_GET_ARTICLES';
export const SUCCESSFUL_DELETE_ARTICLE = 'SUCCESSFUL_DELETE_ARTICLE';
export const FAILED_DELETE_ARTICLE = 'FAILED_DELETE_ARTICLE';

// Todos los Context
export const SWITCH_LOADING = 'SWITCH_LOADING_LOGIN';